name: build stable version

on:
  push:
    tags: [ v* ]

env:
  IMAGE_NAME: "novalagung/epubcheck"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
