name: 'build'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: construct release tagging
        run: |
          IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/epubcheck:latest"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "building ${IMAGE_TAG}"
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - name: build docker image
        run: |
          docker build . -t "${IMAGE_TAG}"
          docker push "${IMAGE_TAG}"
