name: build stable version

on:
  push:
    tags: [ v* ]

env:
  IMAGE_NAME: "novalagung/epubcheck"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{raw}},enable=${{ github.ref == format('refs/heads/v{0}') }}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}"
